name: CI/CD Pipeline
on:
  push:
    branches: ["main", "dev"]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Test du code (Consigne 2)
      - name: ðŸ§ª Installation et Tests
        run: |
          sudo npm install -g htmlhint
          htmlhint src/index.html

      # (On ajoutera le dÃ©ploiement ici Ã  l'Ã©tape 5)
